#!/bin/bash
VAR=${2}
MAJOR=` echo $VAR | cut -f 1 -d "-" `
VAR=${VAR##$MAJOR"-"}
MINOR=` echo $VAR | cut -f 1 -d "." `
kver=$MAJOR-$MINOR.*
find $3 -name '*.ko' | sed 's|^.*/\([^/]*\)\.ko$|\1|' | sort -u | \
while read -r module; do
	module_subdir=`find $3 -name $module.ko | sed "s|^.*/${1}\(.*\)/${module}\.ko$|\1|"`
	echo "override $module $kver weak-updates/$1$module_subdir"
done
